### ISSUE TITLE
Powershell script downloads 32-bit version on non-English Windows versions

### ISSUE THREAD

**Issue by AdamMir86** [opentofu/get.opentofu.org#37]
### OpenTofu Version

```shell
OpenTofu v1.8.4 on windows_386
```

### OpenTofu Configuration Files

not needed

### Debug Output

```
  ╷
  │ Error: Plugin did not respond
  │
  │   with aws_efs_file_system.this,
  │   on main.tf line 1, in resource "aws_efs_file_system" "this":
  │    1: resource "aws_efs_file_system" "this" {
  │
  │ The plugin encountered an error, and failed to respond to the
  │ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
  │ details.
  ╵

  Stack trace from the terraform-provider-aws.exe plugin:

  panic: Error reading level state: strconv.ParseInt: parsing "2885974016": value out of range

  goroutine 77 [running]:
  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x255ad450, {0x256fdcf0, 0x1, 0x1}, 0x8)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource_data.go:556 +0x271
  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x255ad450)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource_data.go:354 +0x47b
  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x259f73b0, {{{0x1918deb4, 0x256fcfe8}}, {0x152dcb80, 0x25fc0660}})
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:698 +0x1e8
  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x2666e9f0, {0x1918dcd4, 0x25317b00}, 0x261e79e0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:682 +0x41f
  github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadResource(0x255ac230, {0x1918dcd4, 0x25317a40}, 0x261e79e0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-mux@v0.17.0/tf5muxserver/mux_server_ReadResource.go:35 +0x1d6
  github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x255ac500, {0x1918dcd4, 0x25317788}, 0x257007c0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/tf5server/server.go:783 +0x34f
  github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x16dc89e0, 0x255ac500}, {0x1918dcd4, 0x25317788}, 0x25700780, 0x0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:575 +0x98
  google.golang.org/grpc.(*Server).processUnaryRPC(0x25729188, {0x1918dcd4, 0x25317758}, {0x191cb2fc, 0x2521e6c8}, 0x24d90bb8, 0x266ca450, 0x22f63774, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1394 +0xfa0
  google.golang.org/grpc.(*Server).handleStream(0x25729188, {0x191cb2fc, 0x2521e6c8}, 0x24d90bb8)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1805 +0x10cf
  google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1029 +0x8a
  created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 84
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1040 +0x12f

  Error: The terraform-provider-aws.exe plugin crashed!

  This is always indicative of a bug within the plugin. It would be immensely
  helpful if you could report the crash with the plugin's maintainers so that it
  can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

plan or apply should not end for error for existing EFS volume

### Actual Behavior

```
15:44:07.979 STDOUT [eu-central-1\efs_bo] tofu: Planning failed. OpenTofu encountered an error while generating this plan.
15:44:07.979 STDOUT [eu-central-1\efs_bo] tofu:
15:44:07.979 STDERR [eu-central-1\efs_bo] tofu: ╷
15:44:07.979 STDERR [eu-central-1\efs_bo] tofu: │ Error: Plugin did not respond
15:44:07.979 STDERR [eu-central-1\efs_bo] tofu: │
15:44:07.979 STDERR [eu-central-1\efs_bo] tofu: │   with aws_efs_file_system.this,
15:44:07.979 STDERR [eu-central-1\efs_bo] tofu: │   on main.tf line 1, in resource "aws_efs_file_system" "this":
15:44:07.979 STDERR [eu-central-1\efs_bo] tofu: │    1: resource "aws_efs_file_system" "this" {
15:44:07.979 STDERR [eu-central-1\efs_bo] tofu: │
15:44:07.980 STDERR [eu-central-1\efs_bo] tofu: │ The plugin encountered an error, and failed to respond to the
15:44:07.980 STDERR [eu-central-1\efs_bo] tofu: │ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
15:44:07.980 STDERR [eu-central-1\efs_bo] tofu: │ details.
```

### Steps to Reproduce

Switch on EFS module that so far was managed via Terraform
1. run terragrunt run-all apply #while terraform 1.8.2 was installed
2. uninstall terraform
3. install opentofu
4. run terragrunt run-all plan #to verify if ther are some issues
5. run terragrunt run-all apply

### Additional Context

I'm in process of migration from terraform to OpenTofu. As a overhead orchestration tool I use terragrunt (v 0.68.7 ). 
Each projects code that i posses undergo same steps:

1. run terragrunt run-all apply while terraform 1.8.2 was installed
2. uninstall terraform
3. install opentofu
4. run terragrunt run-all plan to verify if ther are some issues
5. run terragrunt run-all apply

Except changes from Terraform to OpenTofu, no other changes being made in such way.

On one project when Tofu is parsing existing tfstate file, I get constant error `Error reading level state: strconv.ParseInt: parsing "2885974016": value out of range`. 

I Looked on that EFS volume and it's not so big slightly more then 2GB in size currently, the size of 
value_in_ia (Infrequent Access storage class) is much grater then on other EFS that I use.
Im reluctant to manually edit tfstate, as probably it will help only once here.

Related tfstate file part that cause issue:
```
    {
      "mode": "managed",
      "type": "aws_efs_file_system",
...
            "size_in_bytes": [
              {
                "value": 2885974016,
                "value_in_ia": 2578825216,
                "value_in_standard": 307148800
              }
            ],
```

Note1: AWS EFS module used AWs module in version 5.50.0
Note2: removing AWS module limitation and upgrading it to 5.74.0 do not resolve issue

**Comment by AdamMir86** [comment]
Your welcome! Glad my issue had helped You a bit
